[package]
name = "multiversx-sc-meta"
version = "0.44.0"
edition = "2021"

authors = [
    "Andrei Marinica <andrei.marinica@multiversx.com>",
    "MultiversX <contact@multiversx.com>",
]
license = "GPL-3.0-only"
readme = "README.md"
repository = "https://github.com/multiversx/mx-sdk-rs"
homepage = "https://multiversx.com/"
documentation = "https://docs.multiversx.com/"
description = "MultiversX smart contract meta-programming tools and build system"
keywords = ["multiversx", "blockchain", "contract", "debug"]
categories = ["cryptography::cryptocurrencies", "development-tools::debugging"]

[[bin]]
name = "sc-meta"
path = "src/main.rs"

[features]
template-test-current = []
template-test-released = []

[dependencies]
reqwest = { version = "0.11.4", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.3.0"
copy_dir = "0.1.2"
zip = { version = "0.6.4", features = ["deflate"], default-features = false }
serde_json = "1.0"
rustc_version = "0.4"
toml = { version = "0.5.8", features = ["preserve_order"] }
ruplacer = { version = "0.8.1", default-features = false }
clap = { version = "4.1.0", features = ["derive"] }
colored = "2.0"
pathdiff = "0.2.1"
common-path = "1.0.0"
lazy_static = "1.4.0"
convert_case = "0.6.0"
hex = "0.4"
wasmparser = "0.116.0"
wasmprinter = "0.2.71"

[dependencies.multiversx-sc]
version = "=0.44.0"
path = "../base"
features = ["alloc", "num-bigint", "promises"]
