[package]
name = "get-at-address-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.get-at-address]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.46.0"
path = "../../../../framework/meta"
default-features = false
