[settings]
main = "alloc-features"

# the only purpose of this config is to specify the allocator
[contracts.alloc-features]
add-unlabelled = true
allocator = "static64k"
stack-size = "32k"

[contracts.alloc-features-fail-memory]
name = "fail-memory"
allocator = "fail"
add-labels = ["fail-memory"]

[contracts.alloc-features-leaking-memory]
name = "leaking-memory"
allocator = "leaking"
add-labels = ["leaking-memory"]
